### ISSUE TITLE
CUDA error: CUBLAS_STATUS_NOT_INITIALIZED when calling `cublasCreate(handle)`

### ISSUE THREAD

**Issue by swb19** [westny/mtp-go#1]
Thank you for your excellent work. I encountered an issue while running train.py on the IND dataset. Have you encountered this before?
![image](https://github.com/westny/mtp-go/assets/58935575/85987a9a-4312-4d02-8e58-760f2aadd1c3)

**Comment by westny** [comment]
A quick Google search suggests it could be related to Cuda memory problems:

https://discuss.pytorch.org/t/cuda-error-cublas-status-not-initialized-when-calling-cublascreate-handle/125450

You could try reducing the batch size as proposed in the thread. I would also play around with the settings for the dataloaders, specifically the settings for pin_memory and persistent_workers arguments which have been the source of problems in the past.
