### ISSUE TITLE
Dataset Problems

### ISSUE THREAD

**Issue by Ezharjan** [westny/mtp-go#3]
Hello, this seems to be a nice work.
But I found that the dataset you utilized is not publically available for the users unless the process of online application containing some questions to be answered with long stories about specific research purposes and detailed information about the applicant. 
I've applied for seeing your dataset by filling all the blanks on your dataset website but there is no response messages nor any prompts hinting the successful submission of the application, to say nothing of the shared links of the datasets available/downloadable. 

<br>

Could you please give some more information about the style and format of the dataset you used in this project? If you can share some lines of your dataset as an example would be much better! 
Thanks!

**Comment by westny** [comment]
Hi, 
Thanks for reaching out. 
Unfortunately, I am not the owner of the Drone datasets, but did apply for them here: https://levelxdata.com/round-dataset/ for example. In my experience, the application does not have to be that extensive and only requires a few lines of text. Usually, they are pretty fast responding to new requests. 
Regarding the format, the data comes as several .csv files for different recordings that contain trajectory information of the tracked agents in the specific scenes. 

When you do receive the data, I would recommend looking at one of my later repositories: https://github.com/westny/dronalize
that is more focused on preprocessing the data in a more flexible format. 

Good luck with your future work!

Theodor

**Comment by Ezharjan** [comment]
> Hi, Thanks for reaching out. Unfortunately, I am not the owner of the Drone datasets, but did apply for them here: https://levelxdata.com/round-dataset/ for example. In my experience, the application does not have to be that extensive and only requires a few lines of text. Usually, they are pretty fast responding to new requests. Regarding the format, the data comes as several .csv files for different recordings that contain trajectory information of the tracked agents in the specific scenes.
> 
> When you do receive the data, I would recommend looking at one of my later repositories: https://github.com/westny/dronalize that is more focused on preprocessing the data in a more flexible format.
> 
> Good luck with your future work!
> 
> Theodor

Thanks!
