### ISSUE TITLE
CUDA version

### ISSUE THREAD

**Issue by zzqqqqzz** [westny/mtp-go#4]
Thank you for sharing. My computer does not support this version of CUDA. Is there a version of the code that works with an older CUDA version, such as CUDA 11.1?

**Comment by westny** [comment]
Have you tried creating an environment with a torch version that works with older versions of cuda?
In the requirements file there is a flag that specifies the cuda version:

` -f https://data.pyg.org/whl/torch-2.0.0+cu117.html``

I assume you need an earlier torch version, such as 1.10.*. The original code was in torch 1 (see earlier commits) which I think should work with most of the code.

**Comment by westny** [comment]
Let me know if you need any more help.

**Comment by westny** [comment]
Let me know if you need any more help.

**Comment by zzqqqqzz** [comment]
OK. I solve this problem by using another computer that meets the CUDA version requirements. Thanks.
