### ISSUE TITLE
the value of p0

### ISSUE THREAD

**Issue by zzqqqqzz** [westny/mtp-go#5]
Thank you for your work. While reading your code for the preprocessing of the rounD dataset, I notice there is a value called p0 in the rounD_preprocess.py, as shown in the image below. Does p0 represent the center of the roundabout? How is the value of p0 obtained?
![图片1](https://github.com/user-attachments/assets/ee48ab80-ec05-425f-9e86-6cddaee65228)

**Comment by westny** [comment]
That is correct. It was obtained by finding the center in the image files and then converting that to the agents' coordinate system. In the [Dronalize](https://github.com/westny/dronalize) toolbox, I use the lane graphs to find the coordinates of the center point instead. With lane graphs, however, there is no need to find out p0 to get the 'polar coordinates' as they serve the same purpose. I would recommend using maps instead.

**Comment by zzqqqqzz** [comment]
Thanks for your reply
