### ISSUE TITLE
Dronalized dataset 

### ISSUE THREAD

**Issue by bob020416** [westny/mtp-go#6]
Hi, i have seen there are another of your work called "dronalized dataset"
i have been working on a  drone dataset and i use dronalized to preprocess my data,

so is it possible to run that format of data on this works ?
if so, can you tell where i might need to modify in the part of code ? 

again thanks for the great works !

**Comment by westny** [comment]
Thank you for your engagement. It is always great to learn that the code is being used!

I am working on adding MTP-GO to the [Dronalize](https://github.com/westny/dronalize) toolbox for comparative studies. It is almost done, but I haven't had the opportunity to verify all implementations as I am currently working on another publication. When it is published, it will appear in the other repository. Stay tuned!

**Comment by bob020416** [comment]
Many thanks, looking forward on your work!

**Comment by westny** [comment]
@bob020416 MTP-GO is now implemented in [Dronalize](https://github.com/westny/dronalize)! Happy coding!
